title="Destination tutorial"

[[tabGroups]]

name="Examples"

[[tabGroups.tabs]]

name="Municipality description"
query="""
PREFIX : <http://destination.example.org/ontology/dest#>

DESCRIBE ?m 
WHERE {
 ?m a :Municipality .
}
LIMIT 1
"""

[[tabGroups.tabs]]

name="Municipalities"
query="""
PREFIX : <http://destination.example.org/ontology/dest#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?posLabel ?pos ?elevation 
WHERE {
 ?m a :Municipality ; 
    geo:defaultGeometry/geo:asWKT ?pos ;
    schema:name ?name ;
    schema:geo/schema:elevation ?elevation .
  
  FILTER(langMatches(lang(?name), 'en'))
  
  BIND(CONCAT(?name, " (", str(?elevation), " m)") AS ?posLabel)
}
"""

[[tabGroups.tabs]]

name="Places by municipality"
query="""
PREFIX : <http://destination.example.org/ontology/dest#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?munName ?placeName
WHERE {
  ?m a :Municipality ; 
     schema:name ?munName ;
     schema:containsPlace ?place .
  
  ?place schema:name ?placeName .
  
  FILTER(langMatches(lang(?munName), 'en') && langMatches(lang(?placeName), 'en'))
  
}
LIMIT 100
"""

[[tabGroups.tabs]]

name="Lodging businesses (limit 500)"
query="""
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX : <http://noi.example.org/ontology/odh#>

SELECT ?h ?pos ?posLabel ?posColor
WHERE {
  ?h a schema:LodgingBusiness ;
     geo:defaultGeometry/geo:asWKT ?pos ;
     schema:name ?posLabel .
  #?h schema:containedInPlace/schema:name "Bozen"@de . # Uncomment for restricting to a municipality
  FILTER (lang(?posLabel) = 'de')

  # Colors
  OPTIONAL {
    ?h a schema:Campground .
    BIND("chlorophyll,0.5" AS ?posColor) # Green
  }
    OPTIONAL {
    ?h a schema:BedAndBreakfast .
    BIND("viridis,0.1" AS ?posColor) # Purple
  }
  OPTIONAL {
    ?h a schema:Hotel .
    BIND("jet,0.3" AS ?posColor) # Light blue
  }
  OPTIONAL {
    ?h a schema:Hostel .
    BIND("jet,0.8" AS ?posColor) # Red
  }
}
LIMIT 500
"""

[[tabGroups.tabs]]

name="Biggest lodging businesses"
query="""
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <http://schema.org/>
PREFIX : <http://destination.example.org/ontology/dest#>

SELECT ?pos ?bName
      (SUM(?nb) AS ?countRoom)
      (SUM(?maxPersons) AS ?countMaxPersons)
      (CONCAT(?bName, ': ', str(?countRoom), ' accommodations, max ', str(?countMaxPersons), ' guests') AS ?posLabel)
WHERE {
  ?b a schema:LodgingBusiness ;
     schema:name ?bName ;
     geo:hasGeometry/geo:asWKT ?pos .

  ?r a schema:Accommodation ;
     schema:containedInPlace ?b ;
     :numberOfUnits ?nb ;
     schema:occupancy [ schema:maxValue ?maxOccupancyPerRoom ] .

  BIND (?nb * ?maxOccupancyPerRoom AS ?maxPersons)
  FILTER (lang(?bName)='en')

}
GROUP BY ?b ?bName ?pos
ORDER BY DESC(?countRoom)
LIMIT 50
"""

