title="Destination tutorial"

[[tabGroups]]

name="Examples"

[[tabGroups.tabs]]

name="Municipality description"
query="""
PREFIX : <http://destination.example.org/ontology/dest#>

DESCRIBE ?m 
WHERE {
 ?m a :Municipality .
}
LIMIT 1
"""

[[tabGroups.tabs]]

name="Municipalities"
query="""
PREFIX : <http://destination.example.org/ontology/dest#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?posLabel ?pos ?elevation 
WHERE {
 ?m a :Municipality ; 
    geo:defaultGeometry/geo:asWKT ?pos ;
    schema:name ?name ;
    schema:geo/schema:elevation ?elevation .
  
  FILTER(langMatches(lang(?name), 'en'))
  
  BIND(CONCAT(?name, " (", str(?elevation), " m)") AS ?posLabel)
}
"""

